'use client';

import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import './cohesive.css';

type DocumentRow={id:string;kind:'rfq'|'product';file_name:string;byte_size:number;status:string;error?:string|null};
type Requirement={id:string;requirement_key:string;section:string;requirement_text:string;source_quote:string;page_number:number|null;category:string;criticality:string;confidence:number;review_status:string;solution_package:string;package_order:number;subcategory:string;subcategory_order:number;compliance_object:string;requirement_type:string;lifecycle_phase:string;evidence_scope:string;expected_evidence:string;manual_match_applicable:number;classification_version:string};
type Evidence={file_name:string;quote:string;location:string};
type Assessment={id:string;requirement_id:string;decision:string;product_name:string;rationale:string;evidence:Evidence[];alternate:{product_name:string;rationale:string}|null;confidence:number;review_status:string;evaluation_method:string};
type Solution={name:string;summary:string;bill_of_material:Array<{item:string;product:string;quantity:number;purpose:string}>;cohesion_checks:Array<{interface:string;status:string;finding:string}>;assumptions:string[];deviations:string[]};
type ExtractionJob={id:string;document_id:string;pipeline_version:string;status:'queued'|'running'|'failed'|'interrupted'|'completed';total_batches:number;completed_batches:number;failed_batches:number;requirements_found:number;progress_percent:number;active_batches:number;pending_batches:number;current_page_range:string|null;error:string|null};
type ComplianceJob={id:string;pipeline_version:string;status:'queued'|'running'|'failed'|'interrupted'|'completed';total_batches:number;completed_batches:number;failed_batches:number;total_requirements:number;completed_requirements:number;deterministic_unknowns:number;ollama_evaluations:number;fireworks_escalations:number;progress_percent:number;active_batches:number;pending_batches:number;current_batch:number|null;error:string|null;stale?:boolean};

const stages=['Sources','Requirements','Compliance','Solution','Outputs'];
const SUBCATEGORY_PAGE_SIZE=20;
const ASSESSMENTS_PER_PAGE=20;
const PIPELINE_API=process.env.NEXT_PUBLIC_PIPELINE_API_URL||'http://127.0.0.1:8000';

export default function Home(){
  const [stage,setStage]=useState(0);const [configured,setConfigured]=useState<boolean|null>(null);const [strategyReady,setStrategyReady]=useState<boolean|null>(null);const [model,setModel]=useState<string|null>(null);
  const [docs,setDocs]=useState<DocumentRow[]>([]);const [requirements,setRequirements]=useState<Requirement[]>([]);const [assessments,setAssessments]=useState<Assessment[]>([]);const [solution,setSolution]=useState<Solution|null>(null);const [extraction,setExtraction]=useState<ExtractionJob|null>(null);const [complianceJob,setComplianceJob]=useState<ComplianceJob|null>(null);
  const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [selected,setSelected]=useState<Requirement|null>(null);const [note,setNote]=useState('');
  const [selectedPackage,setSelectedPackage]=useState('');
  const [subcategoryPages,setSubcategoryPages]=useState<Record<string,number>>({});
  const [assessmentPage,setAssessmentPage]=useState(1);
  const assessmentCountRef=useRef(0);
  const rfqs=docs.filter(d=>d.kind==='rfq');const manuals=docs.filter(d=>d.kind==='product');const currentExtraction=extraction&&extraction.document_id===rfqs[0]?.id?extraction:null;
  const extractionReady=currentExtraction?.status==='completed';
  const extractionId=extraction?.id;const extractionStatus=extraction?.status;
  const complianceId=complianceJob?.id;const complianceStatus=complianceJob?.status;

  const api=useCallback(async(path:string,init?:RequestInit)=>{const response=await fetch(`${PIPELINE_API}${path.replace('/api/pipeline','')}`,init);const data=await response.json();if(!response.ok)throw new Error(data.detail||data.error||'Pipeline request failed.');setError('');return data},[]);
  const refresh=useCallback(async()=>{try{const [s,d,r,c,so,x,cj]=await Promise.all([api('/api/pipeline/status'),api('/api/pipeline/documents'),api('/api/pipeline/requirements'),api('/api/pipeline/compliance'),api('/api/pipeline/solution'),api('/api/pipeline/extractions/latest'),api('/api/pipeline/compliance/jobs/latest')]);setConfigured(s.configured);setStrategyReady(Boolean(s.extraction_strategy));setModel(s.model);setDocs(d.documents);setRequirements(r.requirements);setAssessments(c.assessments);assessmentCountRef.current=c.assessments.length;setSolution(so.solution?.data||null);setExtraction(x.job||null);setComplianceJob(cj.job||null)}catch(e){setError(e instanceof Error?e.message:'Unable to load pipeline state.')}},[api]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh]);
  useEffect(()=>{if(!extractionId||!extractionStatus||!['queued','running'].includes(extractionStatus))return;const poll=async()=>{try{const result=await api(`/api/pipeline/extractions/${extractionId}`);setExtraction(result.job);if(!['queued','running'].includes(result.job.status))await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to read extraction progress.')}};const timer=window.setInterval(()=>void poll(),2000);return()=>window.clearInterval(timer)},[api,extractionId,extractionStatus,refresh]);
  useEffect(()=>{if(!complianceId||!complianceStatus||!['queued','running'].includes(complianceStatus))return;const poll=async()=>{try{const result=await api(`/api/pipeline/compliance/jobs/${complianceId}`);setComplianceJob(result.job);if(result.job.completed_requirements!==assessmentCountRef.current){const decisions=await api('/api/pipeline/compliance');setAssessments(decisions.assessments);assessmentCountRef.current=decisions.assessments.length}if(!['queued','running'].includes(result.job.status))await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to read compliance progress.')}};const timer=window.setInterval(()=>void poll(),2500);return()=>window.clearInterval(timer)},[api,complianceId,complianceStatus,refresh]);

  async function run(label:string,action:()=>Promise<unknown>,after?:()=>void){setBusy(label);setError('');setMessage('');try{await action();await refresh();setMessage(`${label} completed successfully.`);after?.()}catch(e){setError(e instanceof Error?e.message:`${label} failed.`)}finally{setBusy('')}}
  async function upload(file:File,kind:'rfq'|'product'){const body=new FormData();body.append('file',file);body.append('kind',kind);await run(kind==='rfq'?'Uploading RFQ':'Indexing product manual',()=>api('/api/pipeline/documents',{method:'POST',body}))}
  async function startExtraction(documentId:string,force=false){setBusy('Starting requirement extraction');setError('');setMessage('');const body=new URLSearchParams({documentId,force:String(force)});try{const result=await api('/api/pipeline/extract',{method:'POST',body});setExtraction(result.job);setMessage(result.job.status==='completed'?'Extraction is already complete.':'Extraction started in the background. You can leave this page and return later.')}catch(e){setError(e instanceof Error?e.message:'Unable to start extraction.')}finally{setBusy('')}}
  async function startCompliance(force=false){setBusy('Starting controlled compliance');setError('');setMessage('');try{const result=await api(`/api/pipeline/compliance?force=${force}`,{method:'POST'});setComplianceJob(result.job);if(force){setAssessments([]);assessmentCountRef.current=0;setAssessmentPage(1)}setMessage(result.job.status==='completed'?'Compliance analysis is already complete.':'Compliance started in the background and can resume after a restart.')}catch(e){setError(e instanceof Error?e.message:'Unable to start compliance analysis.')}finally{setBusy('')}}
  async function saveRequirement(req:Requirement){await run(`Saving ${req.requirement_key}`,()=>api('/api/pipeline/requirements',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:req.id,requirementText:req.requirement_text,reviewStatus:'Edited',note})}));setSelected(null);setNote('')}
  const packageGroups=useMemo(()=>groupRequirements(requirements),[requirements]);
  const activePackage=packageGroups.find(group=>group.name===selectedPackage)||packageGroups[0]||null;
  const coverage=useMemo(()=>requirements.length?Math.round(assessments.length/requirements.length*100):0,[requirements,assessments]);

  return <main className="live-shell">
    <aside className="live-nav"><div className="live-brand"><span>G</span><div><strong>GridSpec</strong><small>Live RFQ intelligence</small></div></div><nav>{stages.map((s,i)=><button key={s} className={stage===i?'active':''} onClick={()=>setStage(i)}><i>{i+1}</i>{s}<small>{i===0?`${docs.length} sources`:i===1?`${requirements.length} extracted`:i===2?`${assessments.length} decisions`:i===3?(solution?'Generated':'Pending'):'Bid package'}</small></button>)}</nav><div className={`model-state ${configured?'connected':'missing'}`}><span>{configured?'●':'!'}</span><div><strong>{configured?'Model connected':'Model key required'}</strong><small>{configured?model:'FIREWORKS_API_KEY missing'}</small></div></div></aside>
    <section className="live-main"><header><div><small>Live project</small><h1>RFQ compliance workspace</h1></div><div className="live-summary"><span><b>{requirements.length}</b> requirements</span><span><b>{coverage}%</b> assessed</span></div></header>
      <div className="live-stagebar">{stages.map((s,i)=><button key={s} className={stage===i?'active':''} onClick={()=>setStage(i)}><span>{i<stage?'✓':i+1}</span>{s}</button>)}</div>
      {!configured&&<div className="key-warning"><strong>Real processing is not yet enabled</strong><p>Start the Python backend and add <code>FIREWORKS_API_KEY</code> to <code>backend/.env</code>. This application will not create placeholder requirements or compliance results.</p></div>}
      {configured&&strategyReady===false&&<div className="key-warning"><strong>Restart the Python API to activate controlled extraction</strong><p>The UI has updated, but the running backend is still the legacy version. Stop the current demo and run <code>./run-demo.sh</code> before starting another extraction.</p></div>}
      {error&&<div className="pipeline-alert error"><strong>Pipeline stopped</strong><p>{error}</p></div>}{message&&<div className="pipeline-alert success">{message}</div>}{busy&&<div className="pipeline-running"><span></span><div><strong>{busy}</strong><small>Preparing the persisted background job.</small></div></div>}
      {currentExtraction&&<div className={`extraction-progress ${currentExtraction.status} ${currentExtraction.status==='running'&&currentExtraction.completed_batches===0?'awaiting-first':''}`}><div className="progress-copy"><strong>{currentExtraction.status==='completed'?'Requirement extraction complete':currentExtraction.status==='failed'?'Extraction paused after a batch failure':currentExtraction.status==='interrupted'?'Extraction interrupted — ready to resume':currentExtraction.completed_batches===0?'Local parsing and candidate analysis are running':'Requirement extraction in progress'}</strong><small>{currentExtraction.completed_batches===0&&currentExtraction.status==='running'?`${currentExtraction.active_batches} controlled batches active · model interpretation is used only for ambiguous candidates`:`${currentExtraction.completed_batches} of ${currentExtraction.total_batches} batches complete · ${currentExtraction.requirements_found} candidate requirements${currentExtraction.current_page_range?` · processing pages ${currentExtraction.current_page_range}`:''}`}</small>{currentExtraction.error&&<em>{currentExtraction.error}</em>}</div><div className="progress-value"><b>{currentExtraction.progress_percent}%</b><span><i style={{width:`${currentExtraction.progress_percent}%`}}></i></span></div></div>}

      {stage===0&&<section className="live-content"><div className="live-title"><span>Step 1</span><h2>Add real source documents</h2><p>RFQs are parsed locally with page-level citations; the model reviews only ambiguous candidates. Product manuals are indexed into a dedicated vector store for evidence retrieval.</p></div><div className="upload-grid"><UploadCard title="Customer RFQ" description="Upload the specification to extract atomic requirements with quotations and page references." action="Upload RFQ PDF" disabled={!!busy||!configured||strategyReady===false} onFile={f=>upload(f,'rfq')}/><UploadCard title="Product manual" description="Upload each catalog or instruction manual that may support a compliance claim." action="Index manual PDF" disabled={!!busy||!configured} onFile={f=>upload(f,'product')}/></div><div className="source-list"><h3>Evidence workspace</h3>{docs.length===0?<Empty text="No documents have been processed."/>:docs.map(d=><div className="source-item" key={d.id}><span>{d.kind==='rfq'?'RFQ':'MAN'}</span><div><strong>{d.file_name}</strong><small>{d.kind==='rfq'?'Customer requirement source':'Product evidence'} · {(d.byte_size/1024/1024).toFixed(1)} MB</small></div><i>{d.status}</i></div>)}</div>{rfqs.length>0&&currentExtraction?.status!=='completed'&&<button className="run-button" disabled={!!busy||!configured||strategyReady===false||currentExtraction?.status==='queued'||currentExtraction?.status==='running'} onClick={()=>startExtraction(rfqs[0].id)}>{strategyReady===false?'Restart Python API first':currentExtraction&&['failed','interrupted'].includes(currentExtraction.status)?'Run controlled extraction':'Extract requirements from '+rfqs[0].file_name+' →'}</button>}{currentExtraction?.status==='completed'&&<><button className="run-button" onClick={()=>setStage(1)}>Review {currentExtraction.requirements_found} requirements →</button><button className="run-button secondary" disabled={!!busy||strategyReady===false} onClick={()=>startExtraction(rfqs[0].id,true)}>Re-extract with improved pipeline</button></>}</section>}

      {stage===1&&<RequirementsWorkspace requirements={requirements} packageGroups={packageGroups} activePackage={activePackage} subcategoryPages={subcategoryPages} onSelectPackage={name=>{setSelectedPackage(name);setSubcategoryPages({})}} onSetPage={(key,page)=>setSubcategoryPages(current=>({...current,[key]:page}))} onEdit={requirement=>{setSelected(requirement);setNote('')}} onContinue={()=>setStage(2)}/>}

      {stage===2&&<ComplianceWorkspace requirements={requirements} assessments={assessments} complianceJob={complianceJob} extractionReady={extractionReady} manualsCount={manuals.length} busy={!!busy} configured={!!configured} assessmentPage={assessmentPage} onSetPage={setAssessmentPage} onStartCompliance={startCompliance} onReturnSources={()=>setStage(0)} onBuildSolution={()=>run('Cohesive solution generation',()=>api('/api/pipeline/solution',{method:'POST'}),()=>setStage(3))}/>}

      {stage===3&&<section className="live-content"><div className="live-title"><span>Engineer checkpoint 3</span><h2>Review the cohesive solution</h2><p>The solution is assembled from the extracted requirements and evidence-backed assessments. Unresolved interfaces remain visible.</p></div>{!solution?<Empty text="Complete compliance analysis and generate a solution."/>:<><div className="solution-hero"><span>Generated solution</span><h3>{solution.name}</h3><p>{solution.summary}</p></div><div className="solution-columns"><div><h3>Bill of material</h3>{solution.bill_of_material.map((b,i)=><div className="bom-live" key={i}><span>{b.quantity}</span><div><strong>{b.product}</strong><small>{b.item} · {b.purpose}</small></div></div>)}</div><div><h3>Interface and cohesion checks</h3>{solution.cohesion_checks.map((c,i)=><div className="check-live" key={i}><i className={c.status.toLowerCase()}>{c.status==='Pass'?'✓':'!'}</i><div><strong>{c.interface}</strong><small>{c.finding}</small></div></div>)}</div></div><div className="solution-notes"><div><h3>Assumptions</h3>{solution.assumptions.map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Deviations</h3>{solution.deviations.map((x,i)=><p key={i}>• {x}</p>)}</div></div><button className="run-button" onClick={()=>setStage(4)}>Prepare bid outputs →</button></>}</section>}

      {stage===4&&<section className="live-content"><div className="live-title"><span>Final output</span><h2>Export the live analysis</h2><p>Exports are generated from the persisted requirements and compliance decisions—not from sample records.</p></div><div className="output-live"><article><span>CSV</span><h3>Compliance matrix</h3><p>{assessments.length} evidence-backed decisions with products, rationale and confidence.</p><button disabled={!assessments.length} onClick={()=>downloadCsv(requirements,assessments)}>Download compliance CSV</button></article><article><span>JSON</span><h3>Solution package</h3><p>Machine-readable BOM, cohesion checks, assumptions and deviations.</p><button disabled={!solution} onClick={()=>solution&&downloadJson(solution)}>Download solution JSON</button></article></div></section>}
    </section>
    {selected&&<div className="review-drawer"><div className="drawer-head"><div><small>{selected.requirement_key} · {selected.section}</small><h3>Edit requirement</h3></div><button aria-label="Close requirement editor" onClick={()=>setSelected(null)}>×</button></div><div className="drawer-classification"><span>{selected.solution_package}</span><span>{selected.subcategory}</span><span>{selected.lifecycle_phase}</span></div><label>Compliance object</label><p className="drawer-object">{selected.compliance_object}</p><label>Expected compliance evidence</label><p className="drawer-evidence">{selected.expected_evidence}</p><label>Normalized requirement</label><textarea rows={5} value={selected.requirement_text} onChange={e=>setSelected({...selected,requirement_text:e.target.value})}/><label>Exact source quotation</label><blockquote>“{selected.source_quote}”<small>Page {selected.page_number??'not returned'}</small></blockquote><label>Optional change note</label><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain the correction for the audit trail"/><div className="drawer-actions"><button onClick={()=>setSelected(null)}>Cancel</button><button className="approve-live" disabled={!selected.requirement_text.trim()||!!busy} onClick={()=>saveRequirement(selected)}>Save changes</button></div></div>}
  </main>
}

type SubcategoryGroup={name:string;order:number;requirements:Requirement[]};
type PackageGroup={name:string;order:number;requirements:Requirement[];subcategories:SubcategoryGroup[]};

function groupRequirements(requirements:Requirement[]):PackageGroup[]{
  const packages=new Map<string,Requirement[]>();
  for(const requirement of requirements){
    const name=requirement.solution_package||'Generic / Unclassified';
    packages.set(name,[...(packages.get(name)||[]),requirement]);
  }
  return [...packages.entries()].map(([name,items])=>{
    const subcategories=new Map<string,Requirement[]>();
    for(const requirement of items){
      const subcategory=requirement.subcategory||'Generic / Other';
      subcategories.set(subcategory,[...(subcategories.get(subcategory)||[]),requirement]);
    }
    return {name,order:items[0]?.package_order||99,requirements:items,subcategories:[...subcategories.entries()].map(([subcategory,subcategoryItems])=>({name:subcategory,order:subcategoryItems[0]?.subcategory_order||99,requirements:subcategoryItems})).sort((a,b)=>a.order-b.order)};
  }).sort((a,b)=>a.order-b.order);
}

function RequirementsWorkspace({requirements,packageGroups,activePackage,subcategoryPages,onSelectPackage,onSetPage,onEdit,onContinue}:{requirements:Requirement[];packageGroups:PackageGroup[];activePackage:PackageGroup|null;subcategoryPages:Record<string,number>;onSelectPackage:(name:string)=>void;onSetPage:(key:string,page:number)=>void;onEdit:(requirement:Requirement)=>void;onContinue:()=>void}){
  return <section className="live-content requirements-content">
    <div className="live-title"><span>Engineer checkpoint 1</span><h2>Review the requirement story</h2><p>Requirements are ordered as a cohesive solution narrative. Editing is optional; the compliance route shown on each item determines whether the next stage looks for a product manual, system design, deliverable, or test record.</p></div>
    {requirements.length===0?<Empty text="Upload an RFQ and run extraction first."/>:<div className="cohesive-browser">
      <aside className="package-browser-nav"><small>Solution packages</small>{packageGroups.map(group=><button key={group.name} className={activePackage?.name===group.name?'active':''} onClick={()=>onSelectPackage(group.name)}><i>{String(group.order).padStart(2,'0')}</i><span>{group.name}</span><b>{group.requirements.length}</b></button>)}</aside>
      {activePackage&&<div className="package-browser-main">
        <div className="package-breadcrumb">Requirements / Package {String(activePackage.order).padStart(2,'0')}</div>
        <div className="package-heading"><div><span>Solution package</span><h3>{activePackage.name}</h3><p>{activePackage.requirements.length} requirements arranged through {activePackage.subcategories.length} engineering chapters.</p></div><div><b>{activePackage.requirements.length}</b><small>requirements</small></div></div>
        <div className="package-meta"><span>Products</span><span>System design</span><span>Services &amp; deliverables</span><span>Verification</span></div>
        <div className="requirement-chapters">{activePackage.subcategories.map((subcategory,index)=>{
          const key=`${activePackage.name}:${subcategory.name}`;
          const pages=Math.max(1,Math.ceil(subcategory.requirements.length/SUBCATEGORY_PAGE_SIZE));
          const page=Math.min(subcategoryPages[key]||1,pages);
          const visible=subcategory.requirements.slice((page-1)*SUBCATEGORY_PAGE_SIZE,page*SUBCATEGORY_PAGE_SIZE);
          return <details key={subcategory.name} open={index<2}><summary><span><i>{activePackage.order}.{index+1}</i><strong>{subcategory.name}</strong></span><b>{subcategory.requirements.length}</b></summary><div className="chapter-requirements">{visible.map(requirement=><button className="cohesive-requirement-row" key={requirement.id} onClick={()=>onEdit(requirement)}><div className="cohesive-row-head"><span>{requirement.requirement_key}</span><i>{requirement.requirement_type}</i><i>{requirement.lifecycle_phase}</i><b>Edit</b></div><strong>{requirement.requirement_text}</strong><div className="cohesive-row-meta"><span>{requirement.compliance_object}</span><span>Page {requirement.page_number??'—'}</span><span className={`evidence-scope ${requirement.evidence_scope}`}>{requirement.expected_evidence}</span></div></button>)}</div>{pages>1&&<div className="chapter-pagination"><button disabled={page===1} onClick={event=>{event.preventDefault();onSetPage(key,page-1)}}>← Previous</button><span>{(page-1)*SUBCATEGORY_PAGE_SIZE+1}–{Math.min(page*SUBCATEGORY_PAGE_SIZE,subcategory.requirements.length)} of {subcategory.requirements.length}</span><button disabled={page===pages} onClick={event=>{event.preventDefault();onSetPage(key,page+1)}}>Next →</button></div>}</details>
        })}</div>
        <div className="requirement-footer"><span className="classification-note">Classification is deterministic and recalculated whenever a requirement is edited.</span><button className="run-button" onClick={onContinue}>Continue to compliance →</button></div>
      </div>}
    </div>}
  </section>
}

type ComplianceLane='all'|'product'|'design'|'deliverable'|'testing'|'engineer';

function complianceLane(requirement:Requirement|undefined):ComplianceLane{
  if(!requirement)return 'engineer';
  if(requirement.evidence_scope==='system_design')return 'design';
  if(requirement.evidence_scope==='engineering_deliverable')return 'deliverable';
  if(requirement.evidence_scope==='test_report')return 'testing';
  if(requirement.evidence_scope==='engineer_confirmation')return 'engineer';
  return 'product';
}

function displayComplianceStatus(assessment:Assessment,requirement:Requirement|undefined){
  const lane=complianceLane(requirement);
  if(lane==='design')return {label:'Design evidence required',tone:'pending'};
  if(lane==='deliverable')return {label:'Deliverable required',tone:'pending'};
  if(lane==='testing')return {label:'Test evidence required',tone:'pending'};
  if(lane==='engineer')return {label:'Engineer review required',tone:'pending'};
  if(assessment.decision==='Unknown'){
    if(assessment.evaluation_method==='deterministic-no-evidence')return {label:'Evidence insufficient',tone:'unresolved'};
    return {label:'Technical review required',tone:'unresolved'};
  }
  return {label:assessment.decision,tone:assessment.decision.toLowerCase().replace(' ','-')};
}

function ComplianceWorkspace({requirements,assessments,complianceJob,extractionReady,manualsCount,busy,configured,assessmentPage,onSetPage,onStartCompliance,onReturnSources,onBuildSolution}:{requirements:Requirement[];assessments:Assessment[];complianceJob:ComplianceJob|null;extractionReady:boolean;manualsCount:number;busy:boolean;configured:boolean;assessmentPage:number;onSetPage:(page:number|((current:number)=>number))=>void;onStartCompliance:(force?:boolean)=>void;onReturnSources:()=>void;onBuildSolution:()=>void}){
  const [lane,setLane]=useState<ComplianceLane>('all');
  const [expandedAssessment,setExpandedAssessment]=useState<string|null>(null);
  const requirementById=useMemo(()=>new Map(requirements.map(requirement=>[requirement.id,requirement])),[requirements]);
  const orderedRows=useMemo(()=>assessments.map(assessment=>({assessment,requirement:requirementById.get(assessment.requirement_id)})).sort((left,right)=>{
    const leftRequirement=left.requirement;const rightRequirement=right.requirement;
    return (leftRequirement?.package_order??99)-(rightRequirement?.package_order??99)
      ||(leftRequirement?.subcategory_order??99)-(rightRequirement?.subcategory_order??99)
      ||(leftRequirement?.page_number??9999)-(rightRequirement?.page_number??9999)
      ||(leftRequirement?.requirement_key??'').localeCompare(rightRequirement?.requirement_key??'');
  }),[assessments,requirementById]);
  const laneCounts=useMemo(()=>orderedRows.reduce<Record<ComplianceLane,number>>((counts,row)=>{counts.all+=1;counts[complianceLane(row.requirement)]+=1;return counts},{all:0,product:0,design:0,deliverable:0,testing:0,engineer:0}),[orderedRows]);
  const filteredRows=lane==='all'?orderedRows:orderedRows.filter(row=>complianceLane(row.requirement)===lane);
  const pages=Math.max(1,Math.ceil(filteredRows.length/ASSESSMENTS_PER_PAGE));
  const displayPage=Math.min(assessmentPage,pages);
  const visibleRows=filteredRows.slice((displayPage-1)*ASSESSMENTS_PER_PAGE,displayPage*ASSESSMENTS_PER_PAGE);
  const productRows=orderedRows.filter(row=>complianceLane(row.requirement)==='product');
  const compliant=productRows.filter(row=>row.assessment.decision==='Compliant').length;
  const exceptions=productRows.filter(row=>['Conditional','Non-compliant'].includes(row.assessment.decision)).length;
  const unresolved=productRows.filter(row=>row.assessment.decision==='Unknown').length;
  const evidenceDue=orderedRows.length-productRows.length;
  const lanes:Array<{id:ComplianceLane;label:string}>=[{id:'all',label:'All results'},{id:'product',label:'Product compliance'},{id:'design',label:'System design'},{id:'deliverable',label:'Deliverables'},{id:'testing',label:'Testing'},{id:'engineer',label:'Engineer review'}];
  const selectLane=(nextLane:ComplianceLane)=>{setLane(nextLane);onSetPage(1);setExpandedAssessment(null)};
  return <section className="live-content"><div className="live-title"><span>Engineer checkpoint 2</span><h2>Validate evidence against the right compliance object</h2><p>Product capabilities use indexed manuals and controlled model evaluation. System design, supplier deliverables, and verification requirements are routed to their required engineering evidence without unnecessary model calls. Fireworks is reserved for explicit conflicts and consequential non-compliance.</p></div>
    {complianceJob&&<div className={`compliance-progress ${complianceJob.status}`}><div><strong>{complianceJob.stale?'Requirements or manuals changed — re-evaluation required':complianceJob.status==='completed'?'Controlled compliance complete':complianceJob.status==='failed'?'Compliance paused after a batch failure':complianceJob.status==='interrupted'?'Compliance interrupted — checkpoints preserved':'Controlled compliance is running'}</strong><small>{complianceJob.completed_requirements} of {complianceJob.total_requirements} requirements complete · {complianceJob.deterministic_unknowns} deterministic/routed · {complianceJob.ollama_evaluations} Ollama · {complianceJob.fireworks_escalations} Fireworks escalations</small>{complianceJob.error&&<em>{complianceJob.error}</em>}</div><div className="progress-value"><b>{complianceJob.progress_percent}%</b><span><i style={{width:`${complianceJob.progress_percent}%`}}></i></span></div></div>}
    {assessments.length===0?<><Empty text={!extractionReady?'Wait for the current requirement extraction to complete.':manualsCount?(complianceJob&&['queued','running'].includes(complianceJob.status)?'The first checkpointed decisions will appear here shortly.':'Run controlled compliance for all extracted requirements.'):'Add at least one product manual before compliance analysis.'}/>{manualsCount&&(!complianceJob||complianceJob.stale||['failed','interrupted','completed'].includes(complianceJob.status))?<button className="run-button" disabled={busy||!configured||!requirements.length||!extractionReady} onClick={()=>onStartCompliance(false)}>{complianceJob?.stale?'Start updated compliance':complianceJob&&['failed','interrupted'].includes(complianceJob.status)?'Resume failed batches':`Evaluate all ${requirements.length} requirements`} →</button>:!manualsCount?<button className="run-button" onClick={onReturnSources}>Return to Sources →</button>:null}</>:<><div className="compliance-summary" aria-label="Compliance result summary"><div><small>Product compliant</small><b>{compliant}</b></div><div><small>Product exceptions</small><b>{exceptions}</b></div><div><small>Product unresolved</small><b>{unresolved}</b></div><div><small>Engineering evidence due</small><b>{evidenceDue}</b></div><div className={complianceJob?.failed_batches?'has-failures':''}><small>Batch failures</small><b>{complianceJob?.failed_batches||0}</b></div></div>
    <div className="compliance-lanes" role="tablist" aria-label="Compliance evidence lanes">{lanes.map(item=><button key={item.id} role="tab" aria-selected={lane===item.id} onClick={()=>selectLane(item.id)}>{item.label}<b>{laneCounts[item.id]}</b></button>)}</div>
    <div className="compact-compliance-meta"><span><b>{filteredRows.length}</b> results · ordered by package, subcategory and RFQ page</span><span>Showing {filteredRows.length?(displayPage-1)*ASSESSMENTS_PER_PAGE+1:0}–{Math.min(displayPage*ASSESSMENTS_PER_PAGE,filteredRows.length)}</span></div>
    <div className="compact-compliance-table"><table><thead><tr><th>Req.</th><th>Package / category</th><th>Requirement</th><th>Status</th><th>Evidence / route</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{visibleRows.map(({assessment,requirement})=>{
      const status=displayComplianceStatus(assessment,requirement);const isExpanded=expandedAssessment===assessment.id;const evidence=assessment.evidence[0];
      return <Fragment key={assessment.id}><tr><td className="compact-req">{requirement?.requirement_key||'Requirement'}</td><td className="compact-package"><b>{requirement?.solution_package||'Unclassified'}</b><small>{requirement?.subcategory||'Other'}</small></td><td className="compact-clause"><b>{requirement?.requirement_text||'Requirement text unavailable'}</b><small>{requirement?.criticality||'—'} · Page {requirement?.page_number??'—'}</small></td><td><span className={`compact-status ${status.tone}`}>{status.label}</span></td><td className="compact-source">{evidence?<><b>{evidence.file_name}</b><small>{evidence.location}</small></>:<><b>{requirement?.expected_evidence||'Engineering evidence'}</b><small>{assessment.evaluation_method.replaceAll('-',' ')}</small></>}</td><td><button className="compact-expand" aria-expanded={isExpanded} aria-label={`${isExpanded?'Collapse':'Expand'} ${requirement?.requirement_key||'requirement'} details`} onClick={()=>setExpandedAssessment(isExpanded?null:assessment.id)}>{isExpanded?'▴':'▾'}</button></td></tr>{isExpanded&&<tr className="compact-detail"><td colSpan={6}><div><section><strong>Technical rationale</strong><p>{assessment.rationale}</p>{assessment.alternate&&<p className="compact-alternate"><b>Alternate: {assessment.alternate.product_name}</b> — {assessment.alternate.rationale}</p>}</section><section><strong>{assessment.evidence.length?'Verified evidence':`Expected evidence: ${requirement?.expected_evidence||'Engineer confirmation'}`}</strong>{assessment.evidence.length?assessment.evidence.map((item,index)=><blockquote key={index}>“{item.quote}”<small>{item.file_name} · {item.location}</small></blockquote>):<p>{requirement?.manual_match_applicable?'No product passage passed the controlled evidence gates.':'Supply the routed engineering evidence to complete this determination.'}</p>}<small>{assessment.confidence}% evaluation confidence · {assessment.evaluation_method.replaceAll('-',' ')}</small></section></div></td></tr>}</Fragment>})}</tbody></table></div>
    <div className="requirement-footer"><div className="pagination"><button disabled={displayPage===1} onClick={()=>onSetPage(page=>Math.max(1,page-1))}>← Previous</button><span>Page <b>{displayPage}</b> of {pages}</span><button disabled={displayPage===pages} onClick={()=>onSetPage(page=>Math.min(pages,page+1))}>Next →</button></div>{complianceJob?.status==='completed'&&!complianceJob.stale?<div className="compliance-actions"><button className="run-button secondary" disabled={busy} onClick={()=>onStartCompliance(true)}>Re-evaluate</button><button className="run-button" disabled={busy||!configured} onClick={onBuildSolution}>Build cohesive solution →</button></div>:complianceJob?.stale?<button className="run-button" disabled={busy} onClick={()=>onStartCompliance(false)}>Start updated compliance →</button>:complianceJob&&['failed','interrupted'].includes(complianceJob.status)?<button className="run-button" disabled={busy} onClick={()=>onStartCompliance(false)}>Resume failed batches →</button>:null}</div></>}
  </section>
}

function UploadCard({title,description,action,disabled,onFile}:{title:string;description:string;action:string;disabled:boolean;onFile:(f:File)=>void}){return <article className="upload-live"><span>PDF</span><h3>{title}</h3><p>{description}</p><label className={disabled?'disabled':''}>{action}<input type="file" accept="application/pdf" disabled={disabled} onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f);e.target.value=''}}/></label></article>}
function Empty({text}:{text:string}){return <div className="empty-live"><span>◇</span><strong>{text}</strong><small>The pipeline will populate this area after the preceding step completes.</small></div>}
function downloadCsv(reqs:Requirement[],items:Assessment[]){const esc=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const rows=[['Requirement','Solution package','Subcategory','Compliance object','Requirement type','Lifecycle phase','Expected evidence','Text','Decision','Product','Rationale','Evidence','Confidence'],...items.map(a=>{const r=reqs.find(x=>x.id===a.requirement_id);return[r?.requirement_key||a.requirement_id,r?.solution_package||'',r?.subcategory||'',r?.compliance_object||'',r?.requirement_type||'',r?.lifecycle_phase||'',r?.expected_evidence||'',r?.requirement_text||'',a.decision,a.product_name,a.rationale,a.evidence.map(e=>`${e.file_name}: ${e.quote}`).join(' | '),a.confidence]})];download('gridspec-compliance.csv',rows.map(r=>r.map(esc).join(',')).join('\n'),'text/csv')}
function downloadJson(data:unknown){download('gridspec-solution.json',JSON.stringify(data,null,2),'application/json')}
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
